dataset_name: 'BV'
train_root: '/data/dcb/bv/FrameWithTextData'
train_file: '/home/dcb/code/bv/CNXCLIP/dataset/train_bv.txt'
val_root: '/data/dcb/bv/FrameWithTextData'
val_file: '/home/dcb/code/bv/CNXCLIP/dataset/val_bv.txt'
freeze: 'None'
INIT_LR: 1.0e-4

