dataset_name: 'BV'
train_root: '../VisualSearch/BV_Frame'
train_file: '/home/dcb/code/bv/CNXCLIP/dataset/train_bv.txt'
val_root: '../VisualSearch/BV_Frame'
val_file: '/home/dcb/code/bv/CNXCLIP/dataset/val_bv_pro.txt'

test_root: '../VisualSearch/BV_Frame'
test_file: '/home/dcb/code/bv/CNXCLIP/dataset/val_bv_pro.txt'

freeze: 'image'
read_local_data: True

model_name: 'GIT_BASE'
vtm: False
dense: False
sparse: False
image_res: 224
batch_size_train: 8
vision_width: 1024
batch_size_test: 8
k_test: 128
num_frm_test: 4
alpha: 0.4
warm_up: True


optimizer: { opt: adamW, lr1: 1.0e-4, lr2: 5.0e-6, weight_decay: 0.02 }
schedular:
  {
    sched: cosine,
    lr: 1.0e-4,
    epochs: 8,
    min_lr: 1.0e-6,
    decay_rate: 1,
    warmup_lr: 1.0e-5,
    warmup_epochs: 4,
    cooldown_epochs: 0,
  }
use_checkpoint: true


