dataset_name: 'BV'
train_root: '/data/dcb/VisualSearch/vatex_train/ImageData'
train_file: '/data/dcb/VisualSearch/vatex_train/TextData/vatex_train.rawcaption_ch.txt'

val_root: '/data/dcb/VisualSearch/vatex_val/ImageData'
val_file: '/data/dcb/VisualSearch/vatex_val/TextData/vatex_val.rawcaption_ch_pro.txt'

test_root: '/data/dcb/VisualSearch/vatex_val/ImageData'
test_file: '/data/dcb/VisualSearch/vatex_val/TextData/vatex_val.rawcaption_ch_pro.txt'

freeze: 'image'
read_local_data: True

model_name: 'GIT_BASE_VATEX'
vtm: True
dense: False
image_res: 224
batch_size_train: 8
vision_width: 1024
batch_size_test: 8
k_test: 128
num_frm_test: 4

alpha: 0.4
warm_up: True


optimizer: { opt: adamW, lr1: 1.0e-4, lr2: 5.0e-6, weight_decay: 0.02 }
schedular:
  {
    sched: cosine,
    lr: 1.0e-4,
    epochs: 8,
    min_lr: 1.0e-6,
    decay_rate: 1,
    warmup_lr: 1.0e-4,
    warmup_epochs: 4,
    cooldown_epochs: 0,
  }
use_checkpoint: true


